name: Targeter
version: 1.0.0
api-version: 1.20
author: Prride
main: me.prride.targeter.Targeter
description: Gives you the ability to choose which entities target you.
commands:
    targetadd:
        description: Add targets to the list.
        usage: /targeteradd <player> <entity>
        permission: targeter.command.add
    targetremove:
        description: Remove targets from the list.
        usage: /targeterremove <player> <entity>
        permission: targeter.command.remove